<div class="post-comic-head"></div>
<div class="post-comic">
  <div class="comicarchiveframe">
    <a href="<?php the_permalink() ?>"><?php do_action('show_archive') ?></a>
    <br />
    <h3><a href="<?php the_permalink() ?>"><?php the_title() ?></a></h3>
    <small><?php the_time('F jS, Y') ?></small></a>
  </div>
  <br class="clear-margins" />          
</div>
<div class="post-comic-foot"></div>